version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      MONGO_URI: mongodb+srv://harshitbehl671:MpHarSHd1TTYdDhC@scatchcluster.koxqw.mongodb.net/scatch?retryWrites=true&w=majority&appName=ScatchCluster

  frontend:
    build:
      context: ./frontend 
      dockerfile: Dockerfile
    container_name: frontend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend